version: "3.7"

services:
  node:
    container_name: vue-node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "8080-8089:8080-8089"
    command: "vue ui --host=0.0.0.0 --port=8000"
    restart: always
    tty: true
    volumes:
      - ./app:/app
    environment:
      TZ: Asia/Tokyo
